name: rippers
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35890565998852253
title: rippers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d7d7d7'
    - '#b4b4b4'
    - '#636363'
  brandStrength: 0.05949503555893898
  lightness: 0.7758962162770331
  saturation: 0.375
  rhythmicContrast: 0.6134241267573088
purpose: []
